infra-net-setup: don't preserve permissions on any platform
casper-network/cctl pull request #12
Opened 2024-04-22 17:16 UTC by marijanp

2024-05-01 18:13 UTC, asladeofgreen requested changes
`cp --no-preserve=mode` fails on MacOSX.  Is there a workaround ?

2024-05-03 20:20 UTC, marijanp commented
Oh, the problem seems to be that `/usr/bin/cp` on macos is not the same as `coreutils`'s `cp` command.

2024-06-07 14:16 UTC, koxu1996 commented
If `--no-preserve=mode` on macOS is missing, then it can be replaced with:

```sh
cat input_file > output_with_default_perms
```

or

```sh
cp input_file > output
chmod 644
```

However, I am not sure why discarding permissions is necessary at all. From [here](https://github.com/cspr-rad/kairos/pull/72#discussion_r1616944197):

> If we don't use --no-preserve=mode we run into permission problems, since the chainspec files come from the Nix store, and those files are owned by root.

@marijanp So is it about ownership, or permissions?

2024-06-10 05:57 UTC, marijanp commented
It's about both, the ownership is already adjusted but not the file permissions. We need write permissions too. I've tried to avoid an additional step but now I've updated it to use chmod

2024-06-10 08:30 UTC, koxu1996 commented
> It's about both, the ownership is already adjusted but not the file permissions.

I assume the file permissions are set to 644, so changing ownership should be sufficient. I'm wondering why #2 was even introduced - are you certain that a plain 'cp' without extra steps doesn't work?

2024-06-10 10:16 UTC, marijanp commented
@koxu1996 The asset files are in the nix-store which is read-only and owned by root. simply using `cp` causes a permission denied error at runtime. using `no-preserve=mode` adjusts both the ownership and the file permission to whatever permission the directory has you are copying to, which is in the case for cctl commands the current working directory

2024-06-10 15:30 UTC, koxu1996 commented
@marijanp Okay, it seems Nix stores files with `444` permission. I was also wondering why we need to modify chainspec, but I see it's the [template that gets modified](https://github.com/casper-network/cctl/blob/ec014c13781d779738922dd1dd283435b04a1740/cmds/infra/net/setup.sh#L240-L248).

I have no other concerns, thanks!

2024-06-24 15:37 UTC, asladeofgreen commented
LGTM

2024-06-24 15:38 UTC, merged